name: Setup-PowerShell
author: Chuck Fricke
description: Sets up the PowerShell modules required for CRFricke repository CI/CD workflows.

runs:
  using: "composite"
  steps:
    - shell: pwsh
      run: |
        $copyRoot = Join-Path $env:GITHUB_ACTION_PATH -ChildPath 'PowerShell'
        $newModulePath = Join-Path $env:RUNNER_TEMP -ChildPath 'PowerShell' -AdditionalChildPath 'Modules'
        Copy-Item -Path $copyRoot -Destination $env:RUNNER_TEMP -Recurse -Force
        $separator = ':'
        if ($IsWindows)
        {
          $separator = ';'
        }
        if (($env:PSModulePath -split $separator) -notcontains $newModulePath)
        {
          $env:PSModulePath = "$newModulePath"
        }
        Set-ActionVariable 'PSModulePath' "$env:PSModulePath"