name: Tests

on: [workflow_dispatch]

jobs:
  Hosted_ubuntu:
    runs-on: ubuntu-latest
    name: Test Action Linux
    steps:
      - name: Dump $PSModulePath Variable
        run: |
          Write-Output '$PSModulePath:'
          Write-Output ($env:PSModulePath -split ':')
        shell: pwsh

      - name: Setup PowerShell
        uses: CRFricke/Setup-PowerShell@v1.0.7

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Build Version
        run: Get-VersionVariables
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_PREFIX: 'v1.0'

      - name: Dump Environment Variables
        run: |
          Write-Output '$PSModulePath:'
          Write-Output ($env:PSModulePath -split ':')
          Enter-ActionOutputGroup "Dump Environment Variables"
          Write-Output (Get-ChildItem -Path Env:\)
          Exit-ActionOutputGroup
        shell: pwsh
